schema_version = "1.0.0"
id = "holographic_viewport"
version = "0.1.0"
name = "Holographic Viewport"
tagline = "Head-tracked off-axis projection in viewport"
maintainer = "H3mul <phil.d324@gmail.com>"
type = "add-on"

license = ["MIT"]

# Supported Blender versions
blender_version_min = "5.0.0"

platforms = ["windows-x64", "windows-arm64"]

# Description and documentation
description = """
A tool that uses webcam head tracking to provide an off-axis projection effect,
making the 3D viewport look like a holographic window into your display.
"""

# Category of the add-on
tags = ["3D View", "User Interface", "Tracking"]

dependencies = [
    "mediapipe==0.10.32",
    "opencv-python==4.13.0.92",
    "cv2-enumerate-cameras==1.3.3"
]

[permissions]
files = "Required to access internal source files"

[build]
build = "./build"
dist = "./dist"
wheels-path = "./wheels"
